import { MarketingLayout } from "@/components/MarketingLayout";

export default function DisclaimerPage() {
  return (
    <MarketingLayout>
      <div className="pt-24 pb-32">
        <div className="container mx-auto px-4 max-w-3xl">
          <h1 className="text-4xl md:text-5xl font-heading font-bold mb-8">Disclaimer</h1>
          <div className="prose prose-invert max-w-none text-zinc-400">
            <p>The information provided by AI Video Factory OS is for general informational purposes only. All information on the Site is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site.</p>
            
            <h2 className="text-white">AI-Generated Content</h2>
            <p>The videos, scripts, and audio generated by our platform are created using artificial intelligence. As such, they may occasionally contain factual errors, inconsistencies, or unpredictable results. Users are responsible for reviewing and verifying all generated content before publication.</p>
          </div>
        </div>
      </div>
    </MarketingLayout>
  );
}
